### Get all contacts
GET http://localhost:8080/contacts

### Get one contact by query parameter id
GET http://localhost:8080/contacts?id=REPLACE_WITH_CONTACT_ID

### Get one contact by id
GET http://localhost:8080/contacts/REPLACE_WITH_CONTACT_ID
